angular.module('sophe.config', [])
.constant('environment', '@@environment')
.constant('dataServiceBaseUrl', '@@dataServiceBaseUrl')
.constant('fhirServiceBaseUrl', '@@fhirServiceBaseUrl')
.constant('libraryBaseUrl', '@@libraryBaseUrl')
.constant('valueSetServiceBaseUrl', '@@valueSetServiceBaseUrl')
.constant('codeSystemServiceBaseUrl', '@@codeSystemServiceBaseUrl')
.constant('configServiceBaseUrl', '@@configServiceBaseUrl')
.constant('exporterServiceBaseUrl', '@@exporterServiceBaseUrl')
.constant('unitServiceBaseUrl', '@@unitServiceBaseUrl')
;