angular.module('sophe.config', [])
.constant('environment', '@@environment')
.constant('dataServiceBaseUrl', '@@dataServiceBaseUrl')
.constant('fhirServiceBaseUrl', '@@fhirServiceBaseUrl')
.constant('libraryBaseUrl', '@@libraryBaseUrl')
.constant('valueSetServiceBaseUrl', '@@valueSetServiceBaseUrl')
.constant('codeSystemServiceBaseUrl', '@@codeSystemServiceBaseUrl')
.constant('configServiceBaseUrl', '@@configServiceBaseUrl')
.constant('exporterServiceBaseUrl', '@@exporterServiceBaseUrl')
.constant('unitServiceBaseUrl', '@@unitServiceBaseUrl')
.constant('userServiceBaseUrl', '@@userServiceBaseUrl')
.constant('authenticationType', '@@authenticationType')
.constant('dashboardController', '@@dashboardController')
.constant('dashboardView', '@@dashboardView')
.constant('phekbUrl', '@@phekbUrl')
.constant('apiKey', '@@apiKey')
;
